api-version: "1.17"
commands: 
  aerodinamico: ~
  anti_aerodinamico: ~
  bolsillosrotos: ~
  derrochador: ~
  lluviaflechas: ~
  lluviafuego: ~
  mala_calidad: ~
  piesplomo: ~
  torpeza: ~
main: main.MainPlugin
name: CustomEnchants
version: 1.0
author: Juance
website: https://github.com/juance20
